// DOM = DOCUMENT OBJECT MODEL IN JAVASCRIPT
// BOM = BROWSER OBJECT MODEL IN JAVASCRIPT

// NODES, PARENTS, AND CHILDRENS TARGETING IN JAVASCRIPT

console.log('Hello World')


// NODES ME TEXT BHI ATE HN AUR COMMENTS BHI ATE H SB KUCH ATA HE 
// ELEMENTS ME ELEMENT ATE HEN HTML ELEMENTS

document.body.childNodes // YANI SARE KE SARE NODES BATADEGA
document.body.childNodes[1] // YANI DOSRA CHILD NODE MILEGA
document.body.childNodes[1].childNodes // YANI MUJHE ISKE BHI CHILD NODES AGE CHAHYE HN TO WO BHI MILJAYEGE
document.body.firstElementChild // PEHLA ESA CHILD JOKE ELEMENT HO
let cont = document.body.childNodes[1] // YANI VARIABLE BANALIA HE EIK
cont.firstChild // YANI PEHLA CHILD MILEGA JO HMNE SELECT KIA HUA HE JESE YAHA PER CHILDNODES[1] HE NODES AYENGE
cont.firstElementChild // YANI AB ME KEHRAH HO KE MUJHE ESA CHILD CHAHAYE JOKE IK ELEMENT HE ELEMENTS MILENGE
cont.lastElementChild // YANI MUJHE LAST ELEMENT MILEGA CHILD KA
cont.lastElementChild.parentElement // YANI MENE JISKA BHI ELEMENT KAHA HE USKA PARENT ELEMENT AJAYEGA
cont.lastElementChild.style.color = "red"; // YANI AB ISKA COLOR RED HOJAYEGA
cont.lastElementChild.style.backgroundColor = "green"; // YANI AB ISKA BACKGROUND COLOR GREEN HOJAYGA
document.body.firstElementChild.childNodes // SARE ELEMENT NODES MILENGE ELEMENT CHILD KE
document.body.firstElementChild.children // YANI FIRST ELEMENT KE HTML ELEMENTS MILENGE
document.body.firstElementChild.children[3].nextElementSibling // YANI BOX 4 KA AGLA ELEMENT MILEGA YANI BOX 5 MILEGA
document.body.firstElementChild.children[3].previousElementSibling // YANI BOX 4 KA PEHLE ELEMENT MILEGA YANI BOX 3 MILEGA
document.body.firstElementChild.children[3].previousSibling // YANI BOX 4 KA PEHLE NODE MILEGA YANI #TEXT MILEGA KIOKE SPACE KO TEXT KEHTE


// TABLE LINKS === TABLE.ROWS, TABLE.CAPTION, TABLE.THEAD, TABLE.TFOOT, TABLE.TBODIES, TBODY.ROWS, TR.CELLS, TR.SECTIONTOWINDEX, TR.ROWINDEX, TD.CELLINDEX

document.body.children[1] // YANI TABLE KO ACCESS KEREGA 2ND CHILDREN / MAIN ELEMENT KO